<!--
  DDB-FORK: Background shape for one SAVING THROWS entry.

  Redrawn from measurements off the local captures (zoomed 6-14x); all geometry
  below is generated by the arithmetic in this file. No DDB path data is used —
  see the IP hygiene rule in design/README.md.

  WHAT THE CAPTURES SHOW
  ----------------------
  Each save entry is two overlapping shapes, not a rounded rectangle:

  * An elongated horizontal HEXAGON — a bar with angled (chamfered) left and
    right ends — holding the ability abbreviation.
  * A CIRCLE capping the right end, larger than the bar is tall, holding the
    signed modifier. It overlaps the bar rather than sitting beside it.
  * The proficiency pip floats OUTSIDE the bar's left end, clear of both shapes.

  Drawn at the host's real pixel size (viewBox = 0 0 w h) so the angled ends and
  the circle never distort. Sits behind the button's text via
  `position: absolute; inset: 0; pointer-events: none`.
-->
<script lang="ts">
  import type { ClassValue } from 'svelte/elements';

  type Props = {
    class?: ClassValue;
    /** Host width in px, measured by the parent. */
    width?: number;
    /** Host height in px, measured by the parent. */
    height?: number;
    /** Left inset where the hexagon starts — the pip sits in this gutter. */
    gutter?: number;
    /** Diameter of the modifier circle. */
    circle?: number;
  };

  let {
    class: cssClass,
    width = 0,
    height = 0,
    gutter = 20,
    circle = 28,
  }: Props = $props();

  /** Shared half-pixel convention with the other ddb svg shapes. */
  const inset = 0.5;

  let ready = $derived(width > 0 && height > 0);

  /** Circle can never exceed the entry box. */
  let cd = $derived(Math.max(0, Math.min(circle, height - 2 * inset, width)));
  let cr = $derived(cd / 2);

  /** Circle is right-aligned and vertically centred. */
  let ccx = $derived(width - inset - cr);
  let ccy = $derived(height / 2);

  /** The bar is shorter than the entry; the circle stands proud of it. */
  let barH = $derived(Math.max(8, Math.min(height - 2 * inset, cd * 0.62)));
  /** Horizontal run of each angled end. */
  let cut = $derived(Math.min(5, barH / 2));

  let barTop = $derived(ccy - barH / 2);
  let barBottom = $derived(ccy + barH / 2);
  let barLeft = $derived(Math.min(gutter, width / 2));
  /** Runs under the circle so the two shapes read as one joined control. */
  let barRight = $derived(Math.max(barLeft + 2 * cut, ccx));

  let bar = $derived.by(() => {
    if (!ready) {
      return '';
    }
    return [
      `M ${barLeft + cut} ${barTop}`,
      `H ${barRight - cut}`,
      `L ${barRight} ${ccy}`,
      `L ${barRight - cut} ${barBottom}`,
      `H ${barLeft + cut}`,
      `L ${barLeft} ${ccy}`,
      'Z',
    ].join(' ');
  });
</script>

{#if ready}
  <svg
    class={['ddb-save-shape', cssClass]}
    viewBox="0 0 {width} {height}"
    xmlns="http://www.w3.org/2000/svg"
    aria-hidden="true"
    focusable="false"
  >
    <path class="ddb-save-shape__bar" vector-effect="non-scaling-stroke" d={bar} />
    <circle
      class="ddb-save-shape__cap"
      vector-effect="non-scaling-stroke"
      cx={ccx}
      cy={ccy}
      r={cr}
    />
  </svg>
{/if}
